// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI_Niz1u8nnypanxZ-Qy1FPqeVivnbpEI',
    appId: '1:194755288310:web:f22768e839c4e0ddd220d7',
    messagingSenderId: '194755288310',
    projectId: 'notepad-flutter-mini',
    authDomain: 'notepad-flutter-mini.firebaseapp.com',
    storageBucket: 'notepad-flutter-mini.appspot.com',
    measurementId: 'G-6WEEW065JB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOAwf5-HPZ5KNjvhZom08m15sbn2iCl4w',
    appId: '1:194755288310:android:47ba1880c0f4da78d220d7',
    messagingSenderId: '194755288310',
    projectId: 'notepad-flutter-mini',
    storageBucket: 'notepad-flutter-mini.appspot.com',
  );
}
